---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support, cloud manager, bluexp 
summary: Astra Trident는 NetApp에서 관리하며 완벽한 지원이 제공되는 오픈 소스 프로젝트입니다. Astra Trident는 Kubernetes 및 영구 볼륨 프레임워크와 기본적으로 통합되어 NetApp 스토리지 플랫폼을 함께 실행하는 시스템에서 볼륨을 원활하게 프로비저닝 및 관리합니다. 
---
= BlueXP의 Kubernetes 데이터 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident는 NetApp에서 관리하며 완벽한 지원이 제공되는 오픈 소스 프로젝트입니다. Astra Trident는 Kubernetes 및 영구 볼륨 프레임워크와 기본적으로 통합되어 NetApp 스토리지 플랫폼을 함께 실행하는 시스템에서 볼륨을 원활하게 프로비저닝 및 관리합니다. link:https://docs.netapp.com/us-en/trident/index.html["Trident에 대해 자세히 알아보십시오"^].



== 피처

를 사용합니다 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html["BlueXP"^] (Cloud Manager) 및 Trident 운영자를 사용해 구축된 Astra Trident의 호환 버전을 사용하면 * Kubernetes 클러스터 추가 및 관리할 수 있습니다 * link:./task/task-k8s-manage-trident.html["Astra Trident를 설치, 업그레이드 또는 제거합니다"]* link:./task/task-k8s-manage-storage-classes.html["스토리지 클래스를 추가 및 제거합니다"]* link:./task/task-k8s-manage-persistent-volumes.html["영구 볼륨 보기"]* link:./task/task-k8s-manage-remove-cluster.html["Kubernetes 클러스터 제거"] 작업 공간에서 * link:./task/task-kubernetes-enable-services.html["BlueXP 백업 및 복구를 활성화하거나 봅니다"]



== 지원되는 Kubernetes 구축

BlueXP는 다음과 같은 환경에서 실행되는 관리형 Kubernetes 클러스터를 지원합니다.

* link:./requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes Service(Amazon EKS)"]
* link:./requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes Service(AKS)"]
* link:./requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine(GKE)"]




== Astra Trident 구축을 지원했습니다

Astra Trident의 최신 버전 4개 중 하나 link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["Trident 연산자를 사용하여 배포됩니다"^] 필수 항목입니다.


NOTE: 를 사용하여 구축된 Astra Trident `tridentctl` 은(는) 지원되지 않습니다. 를 사용하여 Astra Trident를 구축한 경우 `tridentctl`BlueXP를 사용하여 Kubernetes 클러스터를 관리할 수는 없습니다. 반드시 해야 합니다  다시 설치합니다 link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["Trident 연산자 사용"^] 또는 link:./task/task-k8s-manage-trident.html["BlueXP 사용"].

BlueXP에서 Astra Trident의 최신 버전을 직접 설치하거나 업그레이드할 수 있습니다.

link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["Astra Trident 사전 요구 사항을 검토합니다"^]



== 백엔드 스토리지를 지원합니다

NetApp Astra Trident는 각 Kubernetes 클러스터에 설치해야 하며, Cloud Volumes ONTAP 또는 ONTAP용 Amazon FSx는 클러스터를 위한 백엔드 스토리지로 구성해야 합니다.



== 비용

BlueXP의 Kubernetes 클러스터 _검색_에 대한 비용은 없지만 Cloud Backup Service를 사용하여 영구 볼륨을 백업할 경우 비용이 청구됩니다.
